<?php
/**
 * German translation (PHP translation file, WordPress 6.5+).
 *
 * @package NoFluffAnalytics
 */

return array(
	'domain'       => 'nofluff-analytics',
	'plural-forms' => 'nplurals=2; plural=(n != 1);',
	'language'     => 'de_DE',
	'project-id-version' => 'No Fluff Analytics 1.2.0',
	'messages'     => array(
		'No Fluff Analytics' => 'No Fluff Analytics',
		'No Fluff' => 'No Fluff',
		'Connects this site to the No Fluff dashboard: adds the tracking script to every page and can report form submissions and WooCommerce orders as goals.' => 'Verbindet diese Website mit dem No Fluff Dashboard: bindet das Messskript auf jeder Seite ein und kann abgeschickte Formulare und WooCommerce-Bestellungen als Ziele melden.',
		'That is not a valid site ID. Paste the 24-character ID or the whole snippet from your No Fluff dashboard.' => 'Das ist keine gültige Website-ID. Fügen Sie die 24-stellige ID oder das komplette Snippet aus Ihrem No Fluff Dashboard ein.',
		'That is not a valid order secret. Copy the 64-character secret shown next to the site ID in your No Fluff dashboard.' => 'Das ist kein gültiger Bestell-Schlüssel. Kopieren Sie die 64-stellige Zeichenfolge, die im No Fluff Dashboard neben der Website-ID steht.',
		'Tracking is active. Visits appear in your No Fluff dashboard within the hour.' => 'Die Messung ist aktiv. Besuche erscheinen innerhalb einer Stunde in Ihrem No Fluff Dashboard.',
		'Open dashboard' => 'Dashboard öffnen',
		'Paste the site ID from your No Fluff dashboard (site page → Setup). Pasting the whole snippet works too.' => 'Fügen Sie die Website-ID aus Ihrem No Fluff Dashboard ein (Website-Seite → Setup). Das komplette Snippet funktioniert auch.',
		'Site ID' => 'Website-ID',
		'Order secret' => 'Bestell-Schlüssel',
		'Needed for WooCommerce orders and revenue in the dashboard: it signs each order, so nobody else can report sales for this site. Without it, orders only count as goal conversions. Copy it from the dashboard next to the site ID. Creating a new one there stops orders from counting until you paste it here.' => 'Nötig, damit das Dashboard Bestellungen und Umsatz aus WooCommerce zählt: Er signiert jede Bestellung, damit niemand sonst Verkäufe für diese Website melden kann. Ohne ihn zählen Bestellungen nur als Abschlüsse. Kopieren Sie ihn im Dashboard neben der Website-ID. Wird dort ein neuer erzeugt, zählen Bestellungen erst wieder, wenn Sie ihn hier einfügen.',
		'Your own visits' => 'Eigene Besuche',
		'Do not count logged-in users who can edit content (administrators, editors, authors)' => 'Angemeldete Nutzer mit Bearbeitungsrechten nicht zählen (Administratoren, Redakteure, Autoren)',
		'Goals' => 'Ziele',
		'Report successful form submissions (Contact Form 7, WPForms, Gravity Forms, Elementor) as the event "form_submit"' => 'Erfolgreich abgeschickte Formulare (Contact Form 7, WPForms, Gravity Forms, Elementor) als Ereignis „form_submit“ melden',
		'Report WooCommerce orders as the event "purchase" (order number, total and currency)' => 'WooCommerce-Bestellungen als Ereignis „purchase“ melden (Bestellnummer, Bestellsumme und Währung)',
		'To count them as conversions, add a goal of type "Custom event" with that name in the dashboard. Nothing a visitor types into a form is sent.' => 'Damit sie als Abschlüsse zählen, legen Sie im Dashboard ein Ziel vom Typ „Custom event“ mit diesem Namen an. Eingaben in Formularen werden nie übertragen.',
		'Identity snippet (optional)' => 'Identitäts-Snippet (optional)',
		'Links enquiries and orders on later visits to the campaign a visitor came from, for visitors who agree to statistics in your consent tool. This plugin never loads it itself, because it cannot know whether a visitor agreed.' => 'Ordnet Anfragen und Bestellungen bei späteren Besuchen der Kampagne zu, über die ein Besucher kam, sofern er in Ihrem Einwilligungstool der Statistik zugestimmt hat. Dieses Plugin lädt das Snippet nie selbst, weil es nicht wissen kann, ob ein Besucher zugestimmt hat.',
		'No Fluff can set this up for you. If you do it yourself, paste the snippet below into the statistics category of your consent tool. The tracking script this plugin adds must stay outside the consent tool and keep loading for everyone, or visits before consent are not counted. The snippet stores one random identifier in the visitor\'s browser and sends nothing by itself. For your consent tool\'s service entry: local storage key nf_id, first party, no expiry (the value is renewed after 400 days). Leaving it out changes nothing about the anonymous statistics.' => 'No Fluff richtet das auf Wunsch für Sie ein. Wenn Sie es selbst machen: das Snippet unten in die Statistik-Kategorie Ihres Einwilligungstools einfügen. Das Messskript, das dieses Plugin einbindet, muss außerhalb des Einwilligungstools bleiben und für alle geladen werden, sonst werden Besuche vor der Einwilligung nicht gezählt. Das Snippet speichert eine zufällige Kennung im Browser der Besucher und sendet selbst nichts. Für den Dienst-Eintrag in Ihrem Einwilligungstool: Local-Storage-Schlüssel nf_id, eigene Website (First Party), kein Ablaufdatum (der Wert wird nach 400 Tagen erneuert). Ohne das Snippet ändert sich an der anonymen Statistik nichts.',
		'I placed the identity snippet in my consent tool' => 'Ich habe das Identitäts-Snippet in mein Einwilligungstool eingefügt',
		'Only switches the suggested text for your privacy policy (Settings → Privacy) to the version that covers the identifier. Tracking is the same either way.' => 'Stellt nur den Textvorschlag für Ihre Datenschutzerklärung (Einstellungen → Datenschutz) auf die Fassung mit der Kennung um. An der Messung ändert sich dadurch nichts.',
		/* translators: %s: plugin version */
		'Version %s. The tracking script this plugin adds sets no cookies and stores nothing in the visitor\'s browser.' => 'Version %s. Das Messskript dieses Plugins setzt keine Cookies und speichert nichts im Browser der Besucher.',
		'Settings' => 'Einstellungen',
		'No Fluff Analytics is not tracking yet.' => 'No Fluff Analytics misst noch nicht.',
		'Add your site ID' => 'Website-ID eintragen',
		'This website uses No Fluff Analytics to understand how the site is used and to measure its speed.' => 'Diese Website nutzt No Fluff Analytics, um die Nutzung der Website zu verstehen und ihre Ladezeit zu messen.',
		'For the basic statistics, no cookies are set and nothing is stored in your browser. When you open a page, the address of the page, the referring page, your browser language, the screen width and loading-time measurements are sent to No Fluff. Your IP address and browser identifier are used to form a pseudonymous value that changes every day and cannot be traced back to you. From the browser identifier only the device type and the browser and operating system family are stored, and from the connection only the country; the IP address itself is not stored.' => 'Für die grundlegende Statistik werden keine Cookies gesetzt und nichts in Ihrem Browser gespeichert. Beim Aufruf einer Seite werden die Seitenadresse, die verweisende Seite, Ihre Browsersprache, die Bildschirmbreite und Ladezeit-Messwerte an No Fluff übermittelt. Ihre IP-Adresse und Browserkennung werden verwendet, um einen pseudonymen Wert zu bilden, der sich täglich ändert und nicht auf Sie zurückgeführt werden kann. Aus der Browserkennung werden nur Geräteklasse sowie Browser- und Betriebssystemfamilie gespeichert, aus der Verbindung nur das Land; die IP-Adresse selbst wird nicht gespeichert.',
		'If you place an order, the order number, the order total and the currency are sent to No Fluff so that sales can be counted. Your name, address, payment details and the items you bought are not sent.' => 'Wenn Sie eine Bestellung aufgeben, werden die Bestellnummer, der Bestellwert und die Währung an No Fluff übermittelt, damit Verkäufe gezählt werden können. Ihr Name, Ihre Adresse, Zahlungsdaten und die gekauften Artikel werden nicht übermittelt.',
		'Legal basis: our legitimate interest in analysing and improving this website (Art. 6(1)(f) GDPR).' => 'Rechtsgrundlage ist unser berechtigtes Interesse an der Analyse und Verbesserung dieser Website (Art. 6 Abs. 1 lit. f DSGVO).',
		'If you agree to statistics in our consent banner, a random identifier is stored in your browser\'s local storage (key nf_id, not a cookie). It stays there until you delete this website\'s data in your browser; on your first visit with consent after 400 days it is replaced by a new one. It contains nothing about you and is used only on this website. It is sent to No Fluff with the pages you open, your enquiries and your orders and stored there with them. With each page No Fluff also stores the referring website, your browser language, device type, browser and operating system family and your country (from the connection), so these are linked across your visits as well. This lets us see that several visits come from the same browser, which campaign link (for example an ad or a newsletter) brought you here, and whether a visit ended in an enquiry or an order.' => 'Wenn Sie in unserem Einwilligungsbanner der Statistik zustimmen, wird im lokalen Speicher Ihres Browsers (Local Storage, Schlüssel nf_id, kein Cookie) eine zufällige Kennung abgelegt. Sie bleibt dort, bis Sie die Daten dieser Website in Ihrem Browser löschen; bei Ihrem ersten Besuch mit Einwilligung nach 400 Tagen wird sie durch eine neue ersetzt. Sie enthält nichts über Sie und wird nur auf dieser Website verwendet. Sie wird mit den aufgerufenen Seiten, Ihren Anfragen und Bestellungen an No Fluff übermittelt und dort mit ihnen gespeichert. Zu jeder Seite speichert No Fluff außerdem die verweisende Website, Ihre Browsersprache, Geräteklasse, Browser- und Betriebssystemfamilie sowie Ihr Land (aus der Verbindung); auch diese Angaben werden so über Ihre Besuche hinweg verknüpft. So sehen wir, dass mehrere Besuche vom selben Browser stammen, über welchen Kampagnenlink (zum Beispiel eine Anzeige oder einen Newsletter) Sie gekommen sind und ob ein Besuch zu einer Anfrage oder Bestellung geführt hat.',
		'If you agree during a visit, the pages you opened earlier in that visit are linked to the identifier as well. No Fluff makes this link on its servers from your IP address and browser identifier, neither of which is stored.' => 'Stimmen Sie während eines Besuchs zu, werden auch die Seiten, die Sie zuvor in diesem Besuch aufgerufen haben, mit der Kennung verknüpft. No Fluff stellt diese Verknüpfung auf seinen Servern über Ihre IP-Adresse und Browserkennung her; beide werden nicht gespeichert.',
		'Legal basis for the identifier: your consent (Art. 6(1)(a) GDPR, § 25(1) TDDDG). You can withdraw it at any time in the consent settings of this website; the identifier is then no longer sent, at the latest one day later. Withdrawal does not affect the lawfulness of processing before it. Deleting this website\'s data in your browser removes the identifier.' => 'Rechtsgrundlage für die Kennung ist Ihre Einwilligung (Art. 6 Abs. 1 lit. a DSGVO, § 25 Abs. 1 TDDDG). Sie können sie jederzeit in den Einwilligungseinstellungen dieser Website widerrufen; die Kennung wird dann spätestens nach einem Tag nicht mehr übermittelt. Der Widerruf berührt nicht die Rechtmäßigkeit der bis dahin erfolgten Verarbeitung. Wenn Sie die Daten dieser Website in Ihrem Browser löschen, wird die Kennung entfernt.',
		'No Fluff processes the data on our behalf on servers in the EU. Data about individual visits is deleted 14 months after the end of the month in which it was collected; only aggregated numbers, such as visits per day, are kept.' => 'No Fluff verarbeitet die Daten in unserem Auftrag auf Servern in der EU. Daten zu einzelnen Besuchen werden 14 Monate nach Ende des Monats gelöscht, in dem sie erhoben wurden; erhalten bleiben nur zusammengefasste Zahlen wie Besuche pro Tag.',
	),
);
